#!/bin/zsh
#############################################
# Last change: 2024-04-12 Ariana
# This script creates directories and copies files from the source to the destination
# It's also possible to overwrite the existing file if those are changed 
#############################################

# Change to script directory
cd "$(dirname "$0")"

# Paths to the source directories based on the current working directory (PWD)
sa="resources/system_profiles/admin"
su="resources/system_profiles/user"

# Paths to the available target directories
pa="/Users/Shared/your-directory/"
pu="/Users/Shared/your-directory/"

# Check whether the target directories exist. If not, create them with mkdir.
[[ -d "$pa" ]] || mkdir -p "$pa"
[[ -d "$pu" ]] || mkdir -p "$pu"

# Check if the source directories exist.
if [[ ! -d "$sa" || ! -d "$su" ]]; then
    # Display an error message and exit with code 1 if source directories do not exist.
    echo "The source directories do not exist."
    exit 1
fi

# Copy files from source to destination with sudo to ensure access
cp -R "$sa" "$pa"
cp -R "$su" "$pu"

# Opens the Finder when you are finished
open "$pa"

# Exit the script without errors
exit 0
