#!/bin/zsh
#############################################
# Last change: 2024-01-17 Ariana
# This script creates directories and copies files from the source to the destination
# It's also possible to overwrite the existing file if those are changed 
#############################################

# Paths to source directories
sa="/Volumes/'USB-NAME'/'DIRECTORY'/system_profiles/admin"
su="/Volumes/'USB-NAME'/'DIRECTORY'/system_profiles/user"

# Paths to existing destination directories
pa="/Users/Shared/'DIRECTORY'/"
pu="/Users/Shared/'DIRECTORY'/"

# Check if source directories exist
if [[ ! -e "$sa" || ! -e "$su" ]]; then
    echo "Source directories do not exist."
    exit 1
fi

# Check if destination directories exist, create them if not
[[ -d "$pa" ]] || mkdir -p "$pa"
[[ -d "$pu" ]] || mkdir -p "$pu"

# Copy files from source to destination
# -R: To indicate recursive (including subdirectories) copying of directories
cp -R "$sa" "$pa"
cp -R "$su" "$pu"

# Open the Finder when done
open "$pa"
